name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build shadow jar
        run: ./gradlew clean shadowJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zota-signer-jar
          path: build/libs/*.jar
